# Generated by Django 3.2.9 on 2022-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('Status_Boolean', models.BooleanField()),
                ('Created_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
            ],
        ),
    ]
