# Generated by Django 3.2.14 on 2022-07-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argonapp', '0004_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='argonapp.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='argonapp.state')),
            ],
        ),
    ]
