# Generated by Django 3.2.14 on 2022-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonapp', '0006_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
