# Generated by Django 3.2.14 on 2022-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonapp', '0010_nearby_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('package_price', models.TextField(blank=True, max_length=100, null=True)),
                ('package_life', models.TextField(blank=True, max_length=100, null=True)),
                ('package_type', models.TextField(blank=True, max_length=100, null=True)),
                ('applicable_for', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
